title: Default
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        hero:
          type: tab
          title: Hero

          fields:
            header.hero.enabled:
              type: toggle
              label: Hero
              highlight: 1
              default: 0
              options:
                  1: PLUGIN_ADMIN.ENABLED
                  0: PLUGIN_ADMIN.DISABLED
              validate:
                  type: bool

            # header.an_example_select_box:
            #   type: select
            #   label: Select one of the following
            #   default: one
            #   options:
            #     one: One
            #     two: Two
            #     three: Three